import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import Sidebar from "@/components/sidebar/sidebar";
import AuthSessionProvider from "@/providers/auth-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthSessionProvider>
          <div className="flex h-full">
            <aside className="flex-[175px] w-[175px] flex-grow-0 border-r border-solid border-r-1 border-[#DBDBDB]">
              <Sidebar />
            </aside>
            <main className="px-10 py-10 w-[70rem] mx-auto">{children}</main>
          </div>
        </AuthSessionProvider>
      </body>
    </html>
  );
}
